apiVersion: v1
kind: Endpoints
metadata:
  name: metrics-server
  namespace: kube-system
subsets:
  - addresses:
      - ip: 10.244.0.39
    ports:
      - port: 443
        protocol: TCP
        name: https
