apiVersion: v1
kind: Service
metadata:
  name: metrics-server
  namespace: kube-system
  labels:
    k8s-app: metrics-server
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 4443
  selector:
    k8s-app: metrics-server
